FROM python:3.8

COPY ./requirements.txt /requirements.txt

RUN python -m pip install -U pip && \
    python -m pip install -r requirements.txt && \
    python -m pip cache purge

WORKDIR /app/

COPY ./src/ /app/src/
 
CMD uvicorn src.api_2:app --host=0.0.0.0